kind: Service
apiVersion: v1
metadata:
  name: java-mp-helidon-example
  labels:
    app: java-mp-helidon-example
spec:
  type: NodePort
  selector:
    app: java-mp-helidon-example
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: java-mp-helidon-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java-mp-helidon-example
        version: v1
    spec:
      containers:
      - name: java-mp-helidon-example
        image: java-mp-helidon-example
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
